/** Official brand colours (hex, no #) for simple-icons used on the site. */
export const BRAND_COLORS: Record<string, string> = {
  nextdotjs: '000000',
  react: '61DAFB',
  angular: '0F0F11',
  vite: '646CFF',
  typescript: '3178C6',
  javascript: 'F7DF1E',
  html5: 'E34F26',
  tailwindcss: '06B6D4',
  shadcnui: '000000',
  threedotjs: '000000',
  webgl: '990000',
  maplibre: '396CB2',
  leaflet: '199900',
  rust: '000000',
  webassembly: '654FF0',
  pwa: '5A0FC8',
  nodedotjs: '5FA04E',
  express: '000000',
  python: '3776AB',
  fastapi: '009688',
  php: '777BB4',
  discord: '5865F2',
  webrtc: '333333',
  modelcontextprotocol: '000000',
  googlegemini: '8E75B2',
  openai: '412991',
  openapiinitiative: '6BA539',
  jsonwebtokens: '000000',
  postgresql: '4169E1',
  mysql: '4479A1',
  mariadb: '003545',
  sqlite: '003B57',
  prisma: '2D3748',
  sequelize: '52B0E7',
  redis: 'FF4438',
  firebase: 'DD2C00',
  docker: '2496ED',
  git: 'F05032',
  github: '181717',
  githubactions: '2088FF',
  linux: 'FCC624',
  ubuntu: 'E95420',
  debian: 'A81D33',
  gnubash: '4EAA25',
  nginx: '009639',
  cloudflare: 'F38020',
  puppeteer: '40B5A4',
  render: '000000',
  lighthouse: 'F44B21',
  windows: '0078D4',
  line: '00C300',
  facebook: '0866FF',
  gmail: 'EA4335',
  astro: 'BC52EE',
};

export type IconName = `lucide:${string}` | `simple-icons:${string}`;

/** Project tag (lower-cased) → icon. Unknown tags fall back to `lucide:tag`. */
const TAG_ICONS: Record<string, IconName> = {
  python: 'simple-icons:python',
  'python 3.12': 'simple-icons:python',
  fastapi: 'simple-icons:fastapi',
  tkinter: 'simple-icons:python',
  pystray: 'simple-icons:python',
  pyinstaller: 'simple-icons:python',
  windows: 'lucide:app-window',
  'windows winrt': 'lucide:app-window',
  'gsmtc api': 'lucide:app-window',
  'desktop app': 'lucide:monitor',
  'discord ipc': 'simple-icons:discord',
  'next.js': 'simple-icons:nextdotjs',
  'next.js 14': 'simple-icons:nextdotjs',
  'next.js 16': 'simple-icons:nextdotjs',
  react: 'simple-icons:react',
  'react 19': 'simple-icons:react',
  angular: 'simple-icons:angular',
  vite: 'simple-icons:vite',
  typescript: 'simple-icons:typescript',
  javascript: 'simple-icons:javascript',
  'html/css': 'simple-icons:html5',
  rust: 'simple-icons:rust',
  webassembly: 'simple-icons:webassembly',
  'three.js': 'simple-icons:threedotjs',
  'maplibre gl': 'simple-icons:maplibre',
  'leaflet.js': 'simple-icons:leaflet',
  leaflet: 'simple-icons:leaflet',
  gtfs: 'lucide:bus',
  postgresql: 'simple-icons:postgresql',
  mysql: 'simple-icons:mysql',
  sqlite: 'simple-icons:sqlite',
  prisma: 'simple-icons:prisma',
  firebase: 'simple-icons:firebase',
  'node.js': 'simple-icons:nodedotjs',
  php: 'simple-icons:php',
  tailwind: 'simple-icons:tailwindcss',
  'tailwind css': 'simple-icons:tailwindcss',
  'shadcn/ui': 'simple-icons:shadcnui',
  'gemini mcp': 'simple-icons:googlegemini',
  'openai api': 'lucide:sparkles',
  pwa: 'simple-icons:pwa',
  'service worker': 'simple-icons:pwa',
  accessibility: 'lucide:accessibility',
  docker: 'simple-icons:docker',
  'render.com': 'simple-icons:render',
  multiplayer: 'lucide:users',
  'game engine': 'lucide:gamepad-2',
  'web audio api': 'lucide:headphones',
  'pdf.js': 'lucide:file-text',
  'canvas api': 'lucide:brush',
  'anime.js': 'lucide:sparkles',
  'systems architecture': 'lucide:layers',
  'web scraping': 'simple-icons:puppeteer',
  mcp: 'simple-icons:modelcontextprotocol',
};

export const tagIcon = (tag: string): IconName => TAG_ICONS[tag.trim().toLowerCase()] ?? 'lucide:tag';

/** Project `icon` field → lucide glyph. */
const PROJECT_ICONS: Record<string, IconName> = {
  train: 'lucide:train-front',
  robot: 'lucide:bot',
  book: 'lucide:book-open',
  register: 'lucide:receipt',
  face: 'lucide:scan-face',
  cake: 'lucide:cake',
  desktop: 'lucide:monitor',
  pdf: 'lucide:file-text',
  cart: 'lucide:shopping-cart',
  gamepad: 'lucide:gamepad-2',
  shoe: 'lucide:footprints',
  film: 'lucide:film',
  beach: 'lucide:palmtree',
  coffee: 'lucide:coffee',
  leaf: 'lucide:leaf',
  crystal: 'lucide:gem',
  bus: 'lucide:bus',
};

export const projectIcon = (icon: string): IconName => PROJECT_ICONS[icon] ?? 'lucide:folder';
